galaxy_info:
  author: Guy Halse
  description: your description
  company: Tertiary Education and Research Network of South Africa
  license: MIT
  min_ansible_version: 2.3
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - eapol_test
    - eduroam
    - wpa_supplicant

dependencies: []
