---
# defaults file for freeradius-eduroam

# Everything below should be overridden, and are here merely to make
# sure we have something to work with when the templating engine runs
eduroam_flr_servers:
  - hostname: flr1.uii.ac.id
    ip: 103.220.113.18
    port: 1812
    secret: MySharedSecret
#  - hostname: flr2.uii.ac.id
#    ip: 155.232.195.21
#    port: 1812
#    secret: MySharedSecret
radius_realm: uii.ac.id
radius_local_users:
  - username: nren_radius_test
    password: PleaseChangeThisPassword

use_pam: no
pam_service_name: radiusd

use_ldap: no
ldap_is_edir: no
ldap_servers:
  - hostname: localhost
    port: 389
    base_dn: dc=example,dc=org
    start_tls: yes

send_cui: yes
send_username: no
